// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA39oVL672fcXuRjSXj9RnNP8yVjuMXpMM',
    appId: '1:103269886948:web:e22dab958f65fcc9cf75f1',
    messagingSenderId: '103269886948',
    projectId: 'iithubai',
    authDomain: 'iithubai.firebaseapp.com',
    storageBucket: 'iithubai.firebasestorage.app',
    measurementId: 'G-JVXETKBP26',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDM5CQGU37P8DGdr2Obifo6BwLAYPlxoKs',
    appId: '1:103269886948:android:fa05df54b9323167cf75f1',
    messagingSenderId: '103269886948',
    projectId: 'iithubai',
    storageBucket: 'iithubai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw81CoEkq4tU36LDM0Gl98ob_bRGRzxgA',
    appId: '1:103269886948:ios:b35261184c0bbdc2cf75f1',
    messagingSenderId: '103269886948',
    projectId: 'iithubai',
    storageBucket: 'iithubai.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDw81CoEkq4tU36LDM0Gl98ob_bRGRzxgA',
    appId: '1:103269886948:ios:b35261184c0bbdc2cf75f1',
    messagingSenderId: '103269886948',
    projectId: 'iithubai',
    storageBucket: 'iithubai.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA39oVL672fcXuRjSXj9RnNP8yVjuMXpMM',
    appId: '1:103269886948:web:c62cebec53d24d4fcf75f1',
    messagingSenderId: '103269886948',
    projectId: 'iithubai',
    authDomain: 'iithubai.firebaseapp.com',
    storageBucket: 'iithubai.firebasestorage.app',
    measurementId: 'G-EPC6S8ZLFD',
  );
}
